version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Indicar al servidor que importe el realm al iniciar (usamos KC_IMPORT para la distribución Quarkus)
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json
    command: ["start-dev"]
    ports:
      - "8080:8080"
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/ecommerce"]
      interval: 10s
      retries: 10
    restart: unless-stopped

# Nota: Keycloak en modo dev expone la consola en http://localhost:8080
# Usa admin/admin para entrar. El compose monta el realm-export.json que crea
# el realm `ecommerce` y un client `ecommerce-module` con secret `ecommerce-secret`.
# Tras levantar, el token endpoint será:
# http://localhost:8080/realms/ecommerce/protocol/openid-connect/token
